Repository delook-dev/delook, pull requests merged in 2025-08, with the labels that each got.

#74 feat: 댑댑댑 서비스 연동, 소개 페이지에 스터디원 모집 내용 작성
  public/images/devdevdev.png
  public/manifest.json
  src/components/ui/DevDevDev.tsx
  src/components/ui/index.ts
  src/pages/about/_content.ts
  src/pages/about/index.tsx
  src/pages/index.tsx
Labels: 기능 추가

#81 docs: pr 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 문서

#82 docs: pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 문서

#84 [chore/SUPINKIM/pin-version] package.json에 volta 버전 명시
  package.json
Labels: chore

#85 chore: version 관련 추가 작업
  .github/workflows/deploy-extension.yml
  .github/workflows/deploy.yml
  .github/workflows/lint-check.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .nvmrc
  .yarnrc.yml
  README.md
  src/pages/about/_content.ts
  src/pages/about/index.tsx
  yarn.lock
Labels: chore
